
name: Testing stuff

on:
  push:
    branches:
      - test

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: contains skip
        env:
          HAS_SKIP: ${{ join(github.event.commits.*.message).contains("#skip") }}
        run: echo "$HAS_SKIP"
      - name: contains zap
        env:
          HAS_ZAP: ${{ join(github.event.commits.*.message).contains("#zap") }}
        run: echo "$HAS_ZAP"

